
services:
  db:
    restart: always
    image: postgres:16-alpine3.20
    container_name: app_postgres
    volumes:
      - ./.database/postgres/data:/var/lib/postgresql/data
    environment:
      - POSTGRES_PASSWORD=qwerty
    ports:
      - 5432:5432

  migrations:
    image: alpine:3.20
    container_name: app_migrations
    volumes:
      - ../migration:/app
    command: /bin/sh -c "apk update && apk add curl && curl -L https://github.com/golang-migrate/migrate/releases/download/v4.15.1/migrate.linux-amd64.tar.gz | tar xvz && ./migrate -path=/app -database=postgres://$$DB_USER:$$DB_PASS@$$DB_HOST:$$DB_PORT/$$DB_NAME?sslmode=disable $$MIGRAT_CMD"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_NAME=postgres
      - DB_PASS=qwerty
      - MIGRAT_CMD=up
    restart: no